
export default interface IProtocolParameters {

    epoch                       : number,
    min_fee_a                   : number,
    min_fee_b                   : number,
    max_block_size              : number,
    max_tx_size                 : number,
    max_block_header_size       : number,
    key_deposit                 : string,
    pool_deposit                : string,
    e_max                       : number,
    n_opt                       : number,
    a0                          : number,
    rho                         : number,
    tau                         : number,
    decentralisation_param      : number,
    extra_entropy               : any,
    protocol_major_ver          : number,
    protocol_minor_ver          : number,
    min_utxo                    : string,
    min_pool_cost               : string,
    nonce                       : string,
    price_mem                   : number,
    price_step                  : number,
    max_tx_ex_mem               : string,
    max_tx_ex_steps             : string,
    max_block_ex_mem            : string,
    max_block_ex_steps          : string,
    max_val_size                : string | number,
    collateral_percent          : number,
    max_collateral_inputs       : number,
    coins_per_utxo_word         : string | number
}